account: https://github.com/kristianmandrup
defaults:
  branch: main
  rootPath: ~
repositories:
  - name: Brand one
    repo: 
      name: brand1
      branch: develop
    docs:
      - docs
      - more-docs
    sidebars:
      - sidebar.js
    blogs:
      - blog
  - name: Brand two
    repo: brand2
    docs:
      - docs
    sidebars:
      - sidebar.js
